### ISSUE TITLE
values.yaml passwords with special characters lead to error

### ISSUE THREAD

**Issue by schroedt** [invoiceninja/dockerfiles#415]
Hi there,

I might have found a bug for invoice ninja:

If you set a user-password at `values.yaml` / `userPassword: "myPassword->WithSpecialCharacters"`, some characters seem not to be allowed:

```

kubectl -n invoice-demo logs -f pod/invoiceninja-6444884b5-ckt6d invoiceninja
2021-12-09T05:34:39Z [INFO] [Entrypoint]: Initialising Invoice Ninja...
Configuration cache cleared!
Configuration cached successfully!
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Files cached successfully!
Nothing to migrate.

2021-12-09T05:34:42Z [INFO] [Entrypoint]: /usr/local/bin/docker-entrypoint: running /docker-entrypoint-init.d/10-init-in.sh
Running DatabaseSeeder
Skipping: already run
Database seeding completed successfully.
[2021-12-09 05:34:45] production.ERROR: The "->" option does not exist. {"exception":"[object] (Symfony\\Component\\Console\\Exception\\RuntimeException(code: 0): The \"->\" option does not exist. at /var/www/app/vendor/symfony/console/Input/ArgvInput.php:115)
[stacktrace]
#0 /var/www/app/vendor/symfony/console/Input/ArgvInput.php(97): Symfony\\Component\\Console\\Input\\ArgvInput->parseShortOptionSet()
invoiceninja/invoiceninja#1 /var/www/app/vendor/symfony/console/Input/ArgvInput.php(78): Symfony\\Component\\Console\\Input\\ArgvInput->parseShortOption()
invoiceninja/invoiceninja#2 /var/www/app/vendor/symfony/console/Input/Input.php(55): Symfony\\Component\\Console\\Input\\ArgvInput->parse()
invoiceninja/invoiceninja#3 /var/www/app/vendor/symfony/console/Command/Command.php(258): Symfony\\Component\\Console\\Input\\Input->bind()
invoiceninja/invoiceninja#4 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
invoiceninja/invoiceninja#5 /var/www/app/vendor/symfony/console/Application.php(978): Illuminate\\Console\\Command->run()
invoiceninja/invoiceninja#6 /var/www/app/vendor/symfony/console/Application.php(295): Symfony\\Component\\Console\\Application->doRunCommand()
invoiceninja/invoiceninja#7 /var/www/app/vendor/symfony/console/Application.php(167): Symfony\\Component\\Console\\Application->doRun()
invoiceninja/invoiceninja#8 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
invoiceninja/invoiceninja#9 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
invoiceninja/invoiceninja#10 /var/www/app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
invoiceninja/invoiceninja#11 {main}
"}


  The "->" option does not exist.


```

**Comment by schroedt** [comment]
Big thanks!

When checking #419, I noticed that characters like `"` are still not allowed. The character is a default one targeting strong passwords. I do recommend updating the implementation to support any chracter.
