### ISSUE TITLE
after update black page and nothing happen

### ISSUE THREAD

**Issue by Tabarane** [invoiceninja/dockerfiles#516]
## Setup
- Version: <v5.6.1-->
- Environment: <Docker-Compose>

## Checklist
- Can you replicate the issue on our v5 demo site https://demo.invoiceninja.com or https://react.invoicing.co/demo? No
- Have you searched existing issues? Yes, not found
- Have you reported this to Slack/forum before posting? No
- Have you inspected the logs in storage/logs/laravel.log for any errors? Yes , nothing updated and nothing showing

## Describe the bug
stable system self-hosted, i regularly update the docker, after this update, black white page and no login

**Comment by Tabarane** [comment]
nothing, i used the same 3 commands for updates , docker stop docker pull docker start nothing more

**Comment by Tabarane** [comment]
i changed to latest mariadb and got the below error

`
2023-06-10 21:24:18 6 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
2023-06-10 21:24:21 6 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
2023-06-10 21:24:21 6 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
2023-06-10 21:24:21 7 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9 to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').
2023-06-10 21:24:21 7 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).

`

**Comment by Tabarane** [comment]
i updated the table and got back to the same error as before, white page with nothing

mariadb ready for connection still nothing working

**Comment by Tabarane** [comment]
error found in laravel.log

```
[previous exception] [object] (PDOException(code: 40001): SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:419)
[stacktrace]
#0 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(419): PDOStatement->execute()
#1 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(753): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\\Database\\Connection->runQueryCallback()
#3 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php(422): Illuminate\\Database\\Connection->run()
#4 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2706): Illuminate\\Database\\Connection->select()
#5 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2694): Illuminate\\Database\\Query\\Builder->runSelect()
#6 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3230): Illuminate\\Database\\Query\\Builder->Illuminate\\Database\\Query\\{closure}()
#7 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2695): Illuminate\\Database\\Query\\Builder->onceWithColumns()
#8 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(296): Illuminate\\Database\\Query\\Builder->get()
#9 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(246): Illuminate\\Database\\Query\\Builder->first()
#10 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(224): Illuminate\\Queue\\DatabaseQueue->getNextAvailableJob()
#11 /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(30): Illuminate\\Queue\\DatabaseQueue->Illuminate\\Queue\\{closure}()
#12 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/DatabaseQueue.php(227): Illuminate\\Database\\Connection->transaction()
#13 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(342): Illuminate\\Queue\\DatabaseQueue->pop()
#14 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(351): Illuminate\\Queue\\Worker->Illuminate\\Queue\\{closure}()
#15 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(160): Illuminate\\Queue\\Worker->getNextJob()
#16 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(148): Illuminate\\Queue\\Worker->daemon()
#17 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(131): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#18 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#19 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(661): Illuminate\\Container\\BoundMethod::call()
#23 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call()
#24 /var/www/app/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute()
#25 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(153): Symfony\\Component\\Console\\Command\\Command->run()
#26 /var/www/app/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run()
#27 /var/www/app/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand()
#28 /var/www/app/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun()
#29 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run()
#30 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run()
#31 /var/www/app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#32 {main}
"} 
```

**Comment by db4rne** [comment]
Hi, I seem to have the same problem, have you found a solution yet?
